


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."livres_auteur" (
    "id" integer NOT NULL,
    "nom" character varying(100) NOT NULL,
    "prenom" character varying(100) NOT NULL,
    "nationalite_id" integer NOT NULL,
    "anneeNaissance" integer
);


ALTER TABLE "public"."livres_auteur" OWNER TO "postgres";


ALTER TABLE "public"."livres_auteur" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."livres_auteur_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."livres_editeur" (
    "id" integer NOT NULL,
    "nom" character varying(200) NOT NULL,
    "adresse" character varying(200) NOT NULL
);


ALTER TABLE "public"."livres_editeur" OWNER TO "postgres";


ALTER TABLE "public"."livres_editeur" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."livres_editeur_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."livres_genre" (
    "id" integer NOT NULL,
    "genre" character varying(50) NOT NULL
);


ALTER TABLE "public"."livres_genre" OWNER TO "postgres";


ALTER TABLE "public"."livres_genre" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."livres_genre_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."livres_illustrateur" (
    "id" integer NOT NULL,
    "nom" character varying(100) NOT NULL,
    "prenom" character varying(100) NOT NULL,
    "nationalite_id" integer NOT NULL
);


ALTER TABLE "public"."livres_illustrateur" OWNER TO "postgres";


ALTER TABLE "public"."livres_illustrateur" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."livres_illustrateur_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."livres_livres" (
    "id" integer NOT NULL,
    "numEdition" integer,
    "numEditeur_id" integer NOT NULL,
    "anneePremiereEdition" integer NOT NULL,
    "titre" character varying(200) NOT NULL,
    "titreVo" character varying(200) DEFAULT NULL::character varying,
    "genre_id" integer NOT NULL,
    "typeLivre_id" integer NOT NULL,
    "dateSaisie" timestamp without time zone,
    "collection" boolean NOT NULL,
    "dateDebutLecture" timestamp without time zone,
    "dateFinLecture" timestamp without time zone,
    "note" real,
    "illustrateur_id" integer,
    "auteur_id" integer,
    "image" character varying(100) DEFAULT NULL::character varying,
    "description" character varying(4000) DEFAULT NULL::character varying,
    "commentaires" character varying(4000) DEFAULT NULL::character varying,
    "serie" character varying(300) DEFAULT NULL::character varying,
    "num_serie" integer,
    "dedicace" character varying(100) DEFAULT NULL::character varying,
    "emprunteur" character varying(200) DEFAULT NULL::character varying
);


ALTER TABLE "public"."livres_livres" OWNER TO "postgres";


ALTER TABLE "public"."livres_livres" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."livres_livres_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."livres_pays" (
    "id" integer NOT NULL,
    "nom" character varying(100) NOT NULL
);


ALTER TABLE "public"."livres_pays" OWNER TO "postgres";


ALTER TABLE "public"."livres_pays" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."livres_pays_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."livres_typelivre" (
    "id" integer NOT NULL,
    "type" character varying(50) NOT NULL
);


ALTER TABLE "public"."livres_typelivre" OWNER TO "postgres";


ALTER TABLE "public"."livres_typelivre" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."livres_typelivre_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."livres_auteur"
    ADD CONSTRAINT "livres_auteur_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."livres_editeur"
    ADD CONSTRAINT "livres_editeur_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."livres_genre"
    ADD CONSTRAINT "livres_genre_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."livres_illustrateur"
    ADD CONSTRAINT "livres_illustrateur_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."livres_livres"
    ADD CONSTRAINT "livres_livres_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."livres_pays"
    ADD CONSTRAINT "livres_pays_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."livres_typelivre"
    ADD CONSTRAINT "livres_typelivre_pkey" PRIMARY KEY ("id");



CREATE INDEX "auteur_id_refs_id_88b45962" ON "public"."livres_livres" USING "btree" ("auteur_id");



CREATE INDEX "livres_auteur_a05fba75" ON "public"."livres_auteur" USING "btree" ("nationalite_id");



CREATE INDEX "livres_illustrateur_a05fba75" ON "public"."livres_illustrateur" USING "btree" ("nationalite_id");



CREATE INDEX "livres_livres_5ff2e9ac" ON "public"."livres_livres" USING "btree" ("illustrateur_id");



CREATE INDEX "livres_livres_bb6eb7cf" ON "public"."livres_livres" USING "btree" ("typeLivre_id");



CREATE INDEX "livres_livres_e57db982" ON "public"."livres_livres" USING "btree" ("numEditeur_id");



CREATE INDEX "livres_livres_f8d711d0" ON "public"."livres_livres" USING "btree" ("genre_id");



ALTER TABLE ONLY "public"."livres_livres"
    ADD CONSTRAINT "auteur_id_refs_id_88b45962" FOREIGN KEY ("auteur_id") REFERENCES "public"."livres_auteur"("id");



ALTER TABLE ONLY "public"."livres_livres"
    ADD CONSTRAINT "genre_id_refs_id_533037e4" FOREIGN KEY ("genre_id") REFERENCES "public"."livres_genre"("id");



ALTER TABLE ONLY "public"."livres_livres"
    ADD CONSTRAINT "illustrateur_id_refs_id_cf9cdc02" FOREIGN KEY ("illustrateur_id") REFERENCES "public"."livres_illustrateur"("id");



ALTER TABLE ONLY "public"."livres_auteur"
    ADD CONSTRAINT "nationalite_id_refs_id_1524a452" FOREIGN KEY ("nationalite_id") REFERENCES "public"."livres_pays"("id");



ALTER TABLE ONLY "public"."livres_illustrateur"
    ADD CONSTRAINT "nationalite_id_refs_id_2b92cc72" FOREIGN KEY ("nationalite_id") REFERENCES "public"."livres_pays"("id");



ALTER TABLE ONLY "public"."livres_livres"
    ADD CONSTRAINT "numEditeur_id_refs_id_f064c7b5" FOREIGN KEY ("numEditeur_id") REFERENCES "public"."livres_editeur"("id");



ALTER TABLE ONLY "public"."livres_livres"
    ADD CONSTRAINT "typeLivre_id_refs_id_135241ad" FOREIGN KEY ("typeLivre_id") REFERENCES "public"."livres_typelivre"("id");



CREATE POLICY "No public access" ON "public"."livres_auteur" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "No public access" ON "public"."livres_editeur" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "No public access" ON "public"."livres_genre" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "No public access" ON "public"."livres_illustrateur" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "No public access" ON "public"."livres_livres" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "No public access" ON "public"."livres_pays" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "No public access" ON "public"."livres_typelivre" TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."livres_auteur" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."livres_editeur" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."livres_genre" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."livres_illustrateur" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."livres_livres" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."livres_pays" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."livres_typelivre" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."livres_auteur" TO "anon";
GRANT ALL ON TABLE "public"."livres_auteur" TO "authenticated";
GRANT ALL ON TABLE "public"."livres_auteur" TO "service_role";



GRANT ALL ON SEQUENCE "public"."livres_auteur_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."livres_auteur_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."livres_auteur_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."livres_editeur" TO "anon";
GRANT ALL ON TABLE "public"."livres_editeur" TO "authenticated";
GRANT ALL ON TABLE "public"."livres_editeur" TO "service_role";



GRANT ALL ON SEQUENCE "public"."livres_editeur_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."livres_editeur_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."livres_editeur_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."livres_genre" TO "anon";
GRANT ALL ON TABLE "public"."livres_genre" TO "authenticated";
GRANT ALL ON TABLE "public"."livres_genre" TO "service_role";



GRANT ALL ON SEQUENCE "public"."livres_genre_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."livres_genre_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."livres_genre_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."livres_illustrateur" TO "anon";
GRANT ALL ON TABLE "public"."livres_illustrateur" TO "authenticated";
GRANT ALL ON TABLE "public"."livres_illustrateur" TO "service_role";



GRANT ALL ON SEQUENCE "public"."livres_illustrateur_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."livres_illustrateur_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."livres_illustrateur_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."livres_livres" TO "anon";
GRANT ALL ON TABLE "public"."livres_livres" TO "authenticated";
GRANT ALL ON TABLE "public"."livres_livres" TO "service_role";



GRANT ALL ON SEQUENCE "public"."livres_livres_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."livres_livres_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."livres_livres_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."livres_pays" TO "anon";
GRANT ALL ON TABLE "public"."livres_pays" TO "authenticated";
GRANT ALL ON TABLE "public"."livres_pays" TO "service_role";



GRANT ALL ON SEQUENCE "public"."livres_pays_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."livres_pays_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."livres_pays_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."livres_typelivre" TO "anon";
GRANT ALL ON TABLE "public"."livres_typelivre" TO "authenticated";
GRANT ALL ON TABLE "public"."livres_typelivre" TO "service_role";



GRANT ALL ON SEQUENCE "public"."livres_typelivre_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."livres_typelivre_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."livres_typelivre_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































