-- Postgres-compatible schema generated from dump.sql
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


DROP TABLE IF EXISTS "livres_auteur" CASCADE;
CREATE TABLE "livres_auteur" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nom" varchar(100) NOT NULL,
  "prenom" varchar(100) NOT NULL,
  "nationalite_id" integer NOT NULL,
  "anneeNaissance" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

DROP TABLE IF EXISTS "livres_editeur" CASCADE;
CREATE TABLE "livres_editeur" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nom" varchar(200) NOT NULL,
  "adresse" varchar(200) NOT NULL,
  PRIMARY KEY ("id")
);

DROP TABLE IF EXISTS "livres_genre" CASCADE;
CREATE TABLE "livres_genre" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "genre" varchar(50) NOT NULL,
  PRIMARY KEY ("id")
);

DROP TABLE IF EXISTS "livres_illustrateur" CASCADE;
CREATE TABLE "livres_illustrateur" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nom" varchar(100) NOT NULL,
  "prenom" varchar(100) NOT NULL,
  "nationalite_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

DROP TABLE IF EXISTS "livres_livres" CASCADE;
CREATE TABLE "livres_livres" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "numEdition" integer DEFAULT NULL,
  "numEditeur_id" integer NOT NULL,
  "anneePremiereEdition" integer NOT NULL,
  "titre" varchar(200) NOT NULL,
  "titreVo" varchar(200) DEFAULT NULL,
  "genre_id" integer NOT NULL,
  "typeLivre_id" integer NOT NULL,
  "dateSaisie" timestamp,
  "collection" boolean NOT NULL,
  "dateDebutLecture" timestamp,
  "dateFinLecture" timestamp,
  "note" real DEFAULT NULL,
  "illustrateur_id" integer DEFAULT NULL,
  "auteur_id" integer DEFAULT NULL,
  "image" varchar(100) DEFAULT NULL,
  "description" varchar(4000) DEFAULT NULL,
  "commentaires" varchar(4000) DEFAULT NULL,
  "serie" varchar(300) DEFAULT NULL,
  "num_serie" integer DEFAULT NULL,
  "dedicace" varchar(100) DEFAULT NULL,
  "emprunteur" varchar(200) DEFAULT NULL,
  PRIMARY KEY ("id")
);



DROP TABLE IF EXISTS "livres_pays" CASCADE;
CREATE TABLE "livres_pays" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nom" varchar(100) NOT NULL,
  PRIMARY KEY ("id")
);

DROP TABLE IF EXISTS "livres_typelivre" CASCADE;
CREATE TABLE "livres_typelivre" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "type" varchar(50) NOT NULL,
  PRIMARY KEY ("id")
);

-- Indexes
CREATE INDEX IF NOT EXISTS "livres_auteur_a05fba75" ON "livres_auteur" ("nationalite_id");
CREATE INDEX IF NOT EXISTS "livres_illustrateur_a05fba75" ON "livres_illustrateur" ("nationalite_id");
CREATE INDEX IF NOT EXISTS "livres_livres_e57db982" ON "livres_livres" ("numEditeur_id");
CREATE INDEX IF NOT EXISTS "livres_livres_f8d711d0" ON "livres_livres" ("genre_id");
CREATE INDEX IF NOT EXISTS "livres_livres_bb6eb7cf" ON "livres_livres" ("typeLivre_id");
CREATE INDEX IF NOT EXISTS "livres_livres_5ff2e9ac" ON "livres_livres" ("illustrateur_id");
CREATE INDEX IF NOT EXISTS "auteur_id_refs_id_88b45962" ON "livres_livres" ("auteur_id");

-- Foreign Key Constraints (added after all tables exist)
ALTER TABLE "livres_auteur" ADD CONSTRAINT "nationalite_id_refs_id_1524a452" FOREIGN KEY ("nationalite_id") REFERENCES "livres_pays" ("id");
ALTER TABLE "livres_illustrateur" ADD CONSTRAINT "nationalite_id_refs_id_2b92cc72" FOREIGN KEY ("nationalite_id") REFERENCES "livres_pays" ("id");
ALTER TABLE "livres_livres" ADD CONSTRAINT "auteur_id_refs_id_88b45962" FOREIGN KEY ("auteur_id") REFERENCES "livres_auteur" ("id");
ALTER TABLE "livres_livres" ADD CONSTRAINT "genre_id_refs_id_533037e4" FOREIGN KEY ("genre_id") REFERENCES "livres_genre" ("id");
ALTER TABLE "livres_livres" ADD CONSTRAINT "illustrateur_id_refs_id_cf9cdc02" FOREIGN KEY ("illustrateur_id") REFERENCES "livres_illustrateur" ("id");
ALTER TABLE "livres_livres" ADD CONSTRAINT "numEditeur_id_refs_id_f064c7b5" FOREIGN KEY ("numEditeur_id") REFERENCES "livres_editeur" ("id");
ALTER TABLE "livres_livres" ADD CONSTRAINT "typeLivre_id_refs_id_135241ad" FOREIGN KEY ("typeLivre_id") REFERENCES "livres_typelivre" ("id");

CREATE POLICY "No public access" ON "livres_livres" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "No public access" ON "livres_auteur" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "No public access" ON "livres_editeur" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "No public access" ON "livres_genre" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "No public access" ON "livres_pays" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "No public access" ON "livres_illustrateur" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "No public access" ON "livres_typelivre" FOR ALL TO authenticated USING (true) WITH CHECK (true);
